// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gichtnvyegvuviliqeuw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdpY2h0bnZ5ZWd2dXZpbGlxZXV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1NDc5NDAsImV4cCI6MjA2ODEyMzk0MH0.PqIaSYxlR33s2Msg403PLBMK5CfNXls2_WHmZo7MwwM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});